### ISSUE TITLE
that is a wordpress portal right?

### ISSUE THREAD

**Issue by RoboMantis** [theWebalyst/safepress#1]
that would be maidsafe running on a wordpress server as an opening for easy adoption?

**Comment by theWebalyst** [comment]
Not at all. I take only inspiration from WordPress. 

SAFEpress will run entirely on SAFENetwork (see http://MaidSafe.net) and will provide similar capabilities to WordPress which runs on the existing internet (but can't run on SAFENetwork).

**Comment by RoboMantis** [comment]
ah gotcha ;D
